### ISSUE TITLE
Case Sensitivity Problem with Package name

### ISSUE THREAD

**Issue by ank91** [natxet/CssMin#13]
Hi !

Composer package names supposed to be in small latter.
I am unable to install your package with composer.

Please read the links.

https://github.com/composer/packagist/issues/186
http://stackoverflow.com/questions/24415965/naming-conventions-when-creating-a-php-composer-package

thanks!

**Comment by natxet** [comment]
I don't know how to change this. If you know how to please guide me.
Thanks!

**Comment by ank91** [comment]
I think this can be done via interface unless it break dependent repositories.
Checkout the link:
http://postimg.org/image/cyhix9xh3/
https://help.github.com/articles/renaming-a-repository/
or google it.

The good news is that i have got success installing your package,was my fault.
I was using 
 "natxet/CssMin": "master"
but
 "natxet/CssMin": "dev-master"
worked for me

**Comment by natxet** [comment]
OK, I don't want to break any dependencies, so I will leave githubs repo name as is.
Thanks,
