### ISSUE TITLE
Minifications breaks animations (add quotes for @keyframes)

### ISSUE THREAD

**Issue by MeSko** [natxet/CssMin#16]
Minifications breaks animation for ie,safari,firefox

css:
```
 @keyframes sk-three-bounce
```
is parsed to:
```
@keyframes "sk-three-bounce"
```

Quotes breaks animation on Firefox and IE

Please fix it.

**Comment by woecifaun** [comment]
Hello,
:+1:
Same for me here.

**Comment by woecifaun** [comment]
Hello,

I made the following PR https://github.com/natxet/CssMin/pull/17 fixing the problem we've got here.

Thank you for your awesome work anyway.
