### ISSUE TITLE
Dublicate selectors not merge

### ISSUE THREAD

**Issue by alexprey** [natxet/CssMin#19]
Before minification, I concatinate a few css files. If this files has the same selectors then result files has a dublicate selectors with dublicates values.

For example:
core.css

```
h1 > a {
   color: blue;
   font-size: 2em;
   text-decoration: underline;
}
```

site.css

```
h1 > a {
   color: #ef0;
   font-size: 1.75em;
}
```

_actual core.css+site.css with minification_

```
h1>a{color:blue;font-size:2em;text-decoration:underline;}h1>a{color:#ef0;font-size:1.75em;}
```

_expected_

```
h1>a{color:#ef0;font-size:1.75em;text-decoration:underline;}
```

**Comment by natxet** [comment]
I think that CssMin code does not provide this functionality of removing duplicate selectors among different files. I am afraid it's a feature that is quite complicated to implement and error prone, but if you need it you can create a pull request with it and we'll review it gladly.
Best,
