### ISSUE TITLE
Move to PSR0/PSR4

### ISSUE THREAD

**Issue by nochso** [natxet/CssMin#20]
This library currently contains 68 classes in a single file. To increase readability and maintainability I want to suggest moving every class to its own file.

If this fork aims to maintain backward compatibility, I'll probably go ahead and fork it.

**Comment by alexprey** [comment]
It's already done. You can see original repository https://code.google.com/p/cssmin/source
But it's a old version and need many time for merge old code with new changes.

I think about splitting on separete files a some month ago, but i don't have time for implement it.

**Comment by nochso** [comment]
Ah, ok. I'll simply fork this project as it's up to date. I propose we make this version 4.0 or alternatively a whole new git repo and composer package to make a clear cut.
